- description.ext
- f/radios/acre2/acre2_clientInit.sqf
- f/radios/acre2/acre2_init.sqf
- f/radios/acre2/acre2_settings.sqf
- f/radios/acre2/acre2_setupPresets.sqf
- f/spect/fn_CamInit.sqf
- f/spect/fn_DrawMarkers.sqf
- f/spect/fn_DrawTags.sqf
- f/spect/fn_OnMapClick.sqf
Shifted all radio frequencies for all factions, Spectator optimization in tags/markers mode.
> ACRE2 Frequencey Shift and Spectator Optimiziation

- f/briefing/f_orbatNotes.sqf
- f/nametag/f_nametags.sqf
> Nametag & Orbat fixes

- f/briefing/f_orbatNotes.sqf
- f/nametag/f_nametags.sqf
Reverts accidental commit into master
> Revert "Nametag & Orbat fixes"

- f/simplewoundingsystem/fn_LifeTick.sqf
- f/simplewoundingsystem/fn_OnDrag.sqf
- f/simplewoundingsystem/fn_SetDowned.sqf
> SWS fixes from #535

- f/setAISkill/f_setAISkill.sqf
- f/setAISkill/fn_setAISkill.sqf
* removed unnecessary pub-var
* tweaked skillSet array & skill levels
* merged random factor into a single variable
> Dev set ai skill

- f/medical/AGM_clientInit.sqf
- f/medical/AGM_converter.sqf
* Now removes proper AGM medical items, in case AGM starts converting medical items before AGM_clientInit can kick in.
* Rebalancing of items handed out in AGM_clientInit.
* Rebalancing of items handed out in AGM_converter.
> Dev agm medical rebalance

- f/assignGear/f_assignGear_aaf.sqf
- f/assignGear/f_assignGear_aaf_b.sqf
- f/assignGear/f_assignGear_csat.sqf
- f/assignGear/f_assignGear_csat_b.sqf
- f/assignGear/f_assignGear_fia.sqf
- f/assignGear/f_assignGear_fia_b.sqf
- f/assignGear/f_assignGear_nato.sqf
- f/assignGear/f_assignGear_nato_b.sqf
Can now be set either individually per loadout type by appending a number ["g",0] call _backpack; or for an entire faction by changing the global variable to the desired value.
> Localized loadout-setting on a per-faction basis.

- f/simplewoundingsystem/fn_LifeTick.sqf
- f/simplewoundingsystem/fn_OnDrag.sqf
- f/simplewoundingsystem/fn_SetDowned.sqf
> SWS fixes only

- f/briefing/f_briefing_aaf.sqf
- f/briefing/f_briefing_admin.sqf
- f/briefing/f_briefing_civ.sqf
- f/briefing/f_briefing_csat.sqf
- f/briefing/f_briefing_fia.sqf
- f/briefing/f_briefing_nato.sqf
- f/briefing/f_loadoutNotes.sqf
- f/briefing/f_orbatNotes.sqf
Thanks to Bear for doing this first!
> Briefing larger section titles

- f/assignGear/fn_assignGear.sqf
Updated assignGear to properly toLower the optional faction input as I could see people getting VERY confused if they did not take letter casing into account.
> Updated assignGear to properly toLower the optional faction input.

- f/assignGear/f_assignGear_aaf.sqf
- f/assignGear/f_assignGear_csat.sqf
- f/assignGear/f_assignGear_fia.sqf
- f/assignGear/f_assignGear_nato.sqf
- f/assignGear/fn_assignGear.sqf
>  Updated some instances where comments where still refering to "Folk"

- f/assignGear/f_assignGear_AI.sqf
- f/briefing/f_briefing_admin.sqf
- f/setAISkill/f_setAISkill.sqf
- f/setAISkill/f_setAISkillValues.sqf
- f/setAISkill/fn_setAISkill.sqf
- f/spect/fn_CamInit.sqf
- f/spect/fn_EventHandler.sqf
- f/zeus/fn_zeusInit.sqf
- init.sqf
Also fixes issue mentioned in #563
> Misc updates

- f/cache/fn_cInit.sqf
- f/cache/fn_cTracker.sqf
- f/cache/fn_gCache.sqf
- f/missionConditions/fn_SetWeather.sqf
* New variables f_var_cacheRun & f_var_cacheSleep to easier control component behavior via debug
* Can now pass aggressiveness directly to f_fnc_gCache as optional param to override global value for individual group
> F3 Caching improvements

- f/assignGear/f_assignGear_AI.sqf
> Fix f_assignGear_AI

- description.ext
- f/setAISkill/f_setAISkill.sqf
- f/setAISkill/fn_setAISkill.sqf
- f/zeus/fn_zeusInit.sqf
* Exclusively server-side now
* Re-adjusted skill levels. "high" is slightly easier, "low" more difficult
* Changed comments deactivating F3 SetAISkill parameter to comment-blocks 
* No longer sets skill for "endurance" as it's not supported in A3
* Reduced random range to +/- 0.08
* Increased initial sleep to 2 seconds, removed unnecessary sleeps elsewhere
> F3 SetAiSkill update

- f/groupJoin/f_groupJoinAction.sqf
* Better response time
* No action "spam" in certain situations (e.g. mountain a vehicle)
> Improved F3 group join

- f/assignGear/f_assignGear_AI.sqf
- f/setAISkill/f_setAISkill.sqf
AssignGear_AI: Allows _defaultclass to ignore non-identified classes
Set AI Skill: Slightly raised accuracy
> Minor tweaks

- f/assignGear/f_assignInsignia.sqf
- f/radios/acre2/acre2_setupPresets.sqf
- f/setGroupID/fn_setGroupID.sqf
Some removal of call compile in heavily used places.
> Optimizations: ACRE2, setGroupID, Insignia

- briefing.sqf
- description.ext
- f/EandEcheck/f_EandECheckLoop.sqf
- f/FTMemberMarkers/fn_LocalFTMarkerSync.sqf
- f/JIP/f_JIP_nearTargetGroupCheck.sqf
- f/assignGear/f_assignGear_aaf.sqf
- f/assignGear/f_assignGear_csat.sqf
- f/assignGear/f_assignGear_fia.sqf
- f/assignGear/f_assignGear_nato.sqf
- f/assignGear/fn_assignGear.sqf
- f/authorisedCrew/fn_authorisedCrewCheck.sqf
- f/briefing/f_briefing_admin.sqf
- f/briefing/f_loadoutNotes.sqf
- f/briefing/f_orbatNotes.sqf
- f/cache/fn_cInit.sqf
- f/cache/fn_cTracker.sqf
- f/casualtiesCap/f_CasualtiesCapCheck.sqf
- f/common/f_setLocalVars.sqf
- f/common/fn_processParamsArray.sqf
- f/dynamicViewDistance/f_setViewDistanceLoop.sqf
- f/groupJoin/f_groupJoinAction.sqf
- f/medical/medical_init.sqf
- f/mpEnd/fn_mpEndReceiver.sqf
- f/radios/radio_init.sqf
- f/removeBody/f_addRemoveBodyEH.sqf
- f/safeStart/f_safeStart.sqf
- f/safeStart/f_safeStartLoop.sqf
- f/setAISkill/f_setAISkillValues.sqf
- f/simplewoundingsystem/fn_OnDamage.sqf
- f/spect/fn_CamInit.sqf
- Fixes parameters in the single-player editor
- Faster
- Redundancy in case paramsArray breaks again.
> Parameter system overhaul

- f/spect/fn_CamInit.sqf
> Minor spectator fixes

- mission.sqm
* All ORBATs have found their inner peace and are more grounded now
* Synd Technical gunner was driving and driver gunning - fixed
> Fixed flying circus

- mission.sqm
* Removed custom pitch from units
> Reducing mission.sqm bloat

- mission.sqm
@ferstaberinde grounded boxes as requested.
> Grounded floating ammo boxes in editor

- description.ext
- stringtable.xml
> Revert "Polish translations"

- f/assignGear/f_assignInsignia.sqf
- f/assignGear/fn_assignGear.sqf
Clarifies insignia styling flag to 'style' from 'island'
> Implements latent Urban CSAT badges

- f/assignGear/f_assignGear_aaf_light.sqf
- f/assignGear/f_assignGear_aaf_standard.sqf
- f/assignGear/f_assignGear_csatPacific_light.sqf
- f/assignGear/f_assignGear_csatPacific_standard.sqf
- f/assignGear/f_assignGear_csat_light.sqf
- f/assignGear/f_assignGear_csat_standard.sqf
- f/assignGear/f_assignGear_ctrg.sqf
- f/assignGear/f_assignGear_ctrg_light.sqf
- f/assignGear/f_assignGear_ctrg_standard.sqf
- f/assignGear/f_assignGear_fiaAK_light.sqf
- f/assignGear/f_assignGear_fiaAK_standard.sqf
- f/assignGear/f_assignGear_fia_light.sqf
- f/assignGear/f_assignGear_fia_standard.sqf
- f/assignGear/f_assignGear_natoPacific_light.sqf
- f/assignGear/f_assignGear_natoPacific_standard.sqf
- f/assignGear/f_assignGear_nato_light.sqf
- f/assignGear/f_assignGear_nato_standard.sqf
- f/assignGear/f_assignGear_syndikat_light.sqf
- f/assignGear/f_assignGear_syndikat_standard.sqf
> assign gear fixes
